name: Build
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build
        run: |
          go build -v -o slackattack

      - name: Cross compile
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          GOOS=windows GOARCH=amd64 go build -o slackattack.exe
          GOOS=darwin GOARCH=amd64 go build -o slackattack-darwin
          GOOS=linux GOARCH=amd64 go build -o slackattack-linux

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            slackattack
            slackattack.exe
            slackattack-darwin
            slackattack-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 