name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Verify files
      run: |
        pwd
        ls -la
    - name: Check file permissions
      run: ls -la requirements.txt
    - name: Install dependencies and fix pip
      run: |
        python -m pip uninstall -y pip
        curl https://bootstrap.pypa.io/get-pip.py -O get-pip.py
        python get-pip.py
        python -m pip install setuptools wheel build
    - name: Build package
      run: |
        python -m build --sdist --wheel --outdir dist --no-isolation
        python -m pip install .
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
