name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  contents: write   

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0   

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Configure Git user
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "GitHub Actions"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel build bump2version

    - name: Set logging level
      run: |
        echo "Setting log level to ${{ github.event.inputs.logLevel }}"
      env:
        LOG_LEVEL: ${{ github.event.inputs.logLevel }}

    - name: Show current directory and files
      run: |
        pwd
        ls -alh

    - name: Extract current version
      id: get_version
      run: echo "::set-output name=version::$(python get_version.py)"

    - name: Bump version and push tag
      run: |
        bump2version patch --current-version ${{ steps.get_version.outputs.version }} --commit --tag --allow-dirty
        git push origin HEAD --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify files
      run: |
        pwd
        ls -la

    - name: Check file permissions
      run: ls -la requirements.txt

    - name: Print Python version
      run: python --version

    - name: Clean build environment
      run: |
        rm -rf dist build

    - name: Verify version before publishing
      run: python -c "import slackattack; print(slackattack.__version__)"

    - name: Build package
      run: |
        python -m build --sdist --wheel --outdir dist --no-isolation
        python -m pip install .

    - name: Conditional step for tags
      if: ${{ github.event.inputs.tags == 'true' }}
      run: |
        echo "Running additional steps for tags scenario."

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
