name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: write  

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Configure Git user
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel build bump2version

    - name: Bump version and push tag
      run: |
        bump2version patch --allow-dirty --commit --tag
        git push origin HEAD --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify files
      run: |
        pwd
        ls -la

    - name: Check file permissions
      run: ls -la requirements.txt

    - name: Print Python version
      run: python --version

    - name: Clean build environment
      run: |
        rm -rf dist

    - name: Build package
      run: |
        python -m build --sdist --wheel --outdir dist --no-isolation
        python -m pip install .

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
